name: Build and push to hosting

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare and clone
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: "euc-01.birdiemail.social"
          username: "root"
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf /var/lib/marti/birdie/prod || true
            mkdir -p /var/lib/marti/birdie/prod
            cd /var/lib/marti/birdie/prod
            git clone --single-branch --branch ${{ github.head_ref || github.ref_name }} https://oauth2:${{ secrets.PAT }}@github.com/MartinGamesCZ/Birdiemail.git .

      - name: Build and restart
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: "euc-01.birdiemail.social"
          username: "root"
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker compose -f /var/lib/marti/birdie/prod/compose.prod.yml down
            cd /var/lib/marti/birdie/prod/package/backend
            /root/.bun/bin/bun install
            /root/.bun/bin/bun run build
            docker compose -f /var/lib/marti/birdie/prod/compose.prod.yml up -d db backend
            cd /var/lib/marti/birdie/prod/package/web
            /root/.bun/bin/bun install
            WEB_TRPC_URL=http://10.74.0.3:3000/trpc NEXT_PUBLIC_TRPC_URL=https://api.birdiemail.social/trpc /root/.bun/bin/bun run build
            docker compose -f /var/lib/marti/birdie/prod/compose.prod.yml up -d web
